-- Users submit bookings after authenticating with Google.
drop table if exists public.bookings cascade;

create table public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  applicant_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  vehicle_number text not null,
  driver_name text not null,
  driver_license text,
  waste_type text not null,
  vehicle_size text not null,
  estimated_weight_tons numeric(10,2) not null check (estimated_weight_tons > 0),
  appointment_at timestamptz not null,
  amount numeric(10,2) not null check (amount >= 0),
  payment_status text not null default 'paid',
  qr_token uuid not null unique,
  checked_in_at timestamptz,
  cancelled_at timestamptz,
  actual_weight_tons numeric(10,2),
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;
alter table public.admins enable row level security;

-- Authenticated users can create their own bookings.
drop policy if exists "users_can_insert_bookings" on public.bookings;
create policy "users_can_insert_bookings"
  on public.bookings
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Users can read their own bookings.
drop policy if exists "users_can_select_own_bookings" on public.bookings;
create policy "users_can_select_own_bookings"
  on public.bookings
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Users can cancel (update) their own bookings.
drop policy if exists "users_can_update_own_bookings" on public.bookings;
create policy "users_can_update_own_bookings"
  on public.bookings
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Admin users can read/update bookings.
drop policy if exists "admins_can_select_bookings" on public.bookings;
create policy "admins_can_select_bookings"
  on public.bookings
  for select
  to authenticated
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins_can_update_bookings" on public.bookings;
create policy "admins_can_update_bookings"
  on public.bookings
  for update
  to authenticated
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- Admins can only read their own admin row.
drop policy if exists "admins_self_select" on public.admins;
create policy "admins_self_select"
  on public.admins
  for select
  to authenticated
  using (user_id = auth.uid());

-- Run this manually after creating your admin auth user:
-- insert into public.admins (user_id) values ('YOUR_AUTH_USER_UUID');
